apiVersion: v1
kind: Pod
metadata:
  name: liveness-nginx
  labels:
    app: web
spec:
  containers:
  - image: nginx
    name: nginx-container
    args:
    - /bin/sh
    - -c
    - touch /tmp/health; sleep 40; rm -rf /tmp/health; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/health
      initialDelaySeconds: 5
      periodSeconds: 5

