apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: db
spec:
  volumes:
    - name: my-vol
      persistentVolumeClaim:
        claimName: my-claim
  containers:
    - name: mongodb
      image: mongo
      ports:
        - containerPort: 27017
          protocol: TCP
      volumeMounts:
        - mountPath: /data/db
          name: my-vol      

